name = "Smith tools"
prefix = "tools"
author = "Smith"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_DE.md",
    "docs/README_PL.md",
    "docs/README.zh-TW.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ace3_ca.paa",
    "meta.cpp"
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip tools_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
