PREP(clearConversions);
PREP(convert);
PREP(convertAll);
PREP(convertAllButSelected);
PREP(convertSelected);
PREP(copyConversionLatest);
PREP(copyConversions);
PREP(createEntities);
PREP(createEntitiesMessage);